# Generated by Django 4.2.2 on 2023-10-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=10000)),
                ('case_title', models.CharField(max_length=10000)),
                ('judged', models.CharField(max_length=10000)),
                ('case_status', models.BooleanField(verbose_name=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
