# Generated by Django 4.2.2 on 2023-11-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0003_remove_scheduling_date_created_scheduling_case_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.scheduling')),
            ],
        ),
    ]
