# Generated by Django 4.2.2 on 2023-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0004_documentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagement',
            name='doc_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
