# Generated by Django 4.2.6 on 2023-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0005_documentmanagement_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
