# Generated by Django 4.2.6 on 2023-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0007_scheduling_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
